import { ethers } from "ethers";

// --- 1. Configure provider & signer ---
const provider = new ethers.JsonRpcProvider("http://127.0.0.1:8545");
const signer = await provider.getSigner(0);

// --- 2. Load ABI generated by Hardhat ---
import ProductNFTJson from "../artifacts/contracts/ProductNFT.sol/ProductNFT.json";

// --- 3. Set deployed contract address ---
// Replace with the address printed when you deployed
const NFT_ADDRESS = "0x5FbDB2315678afecb367f032d93F642f64180aa3";

// --- 4. Create contract instance ---
const productNFT = new ethers.Contract(
  NFT_ADDRESS,
  ProductNFTJson.abi,
  signer
);

// =========================
//    EXPORTED FUNCTIONS
// =========================

/**
 * Mint an NFT representing a product.
 *
 * @param productId The ID of the product
 * @param metadataCID The IPFS CID for metadata (e.g. "ipfs://Qm123")
 */
export async function mint(
  productId: number,
  metadataCID: string
) {
  const tx = await productNFT.mint(productId, metadataCID);
  await tx.wait();
  console.log(`✔ NFT minted for product ${productId}`);
}

/**
 * Get owner of a product NFT by token ID.
 */
export async function getNFTOwner(productId: number) {
  const owner = await productNFT.ownerOf(productId);
  return owner;
}

/**
 * Get the metadata URI (IPFS URI) of a product NFT.
 */
export async function getNFTMetadataURI(productId: number) {
  const uri = await productNFT.tokenURI(productId);
  return uri;
}

/**
 * Return all NFTs owned by a given wallet.
 */
export async function getNFTsByOwner(ownerAddress: string) {
  const filter = productNFT.filters.Transfer(null, ownerAddress);
  const events = await productNFT.queryFilter(filter);

  const ownedIds = events.map((e) => Number(e.args.tokenId));
  return ownedIds;
}
